import earcut from 'earcut';
import polygonClipping from 'polygon-clipping';
import type { GeoAnchor } from '../geo/coordinates.ts';
import { pointInFootprint } from './buildingCoverage.ts';
import type { BuildingFootprint, Point2, WorldMap } from './osm.ts';
import type { Landmark } from './navigation.ts';

/**
 * Separate local ODbL site metadata generated by pnpm map:recover --apply.
 * School grounds are mapped OSM areas, NOT surveyed fences or building walls.
 */
export interface MappedSite {
  sourceId: string;
  kind: string;
  name: string;
  outline: Point2[];
  holes: Point2[][];
}
export interface CampusSiteData {
  schemaVersion: 1;
  source: 'OpenStreetMap';
  collectedAt: string;
  anchor: GeoAnchor;
  sites: MappedSite[];
}
const SCHOOL_KINDS = new Set([
  'amenity:school', 'amenity:college', 'amenity:university',
  'amenity:kindergarten'
]);
const LIMIT = 500;
const RECT: [number, number][] = [
  [-LIMIT, -LIMIT], [LIMIT, -LIMIT],
  [LIMIT, LIMIT], [-LIMIT, LIMIT], [-LIMIT, -LIMIT]
];

const pointValid = (point: unknown): point is Point2 => {
  const p = point as Point2 | null;
  return !!p && Number.isFinite(p.x) && Number.isFinite(p.z) &&
    Math.abs(p.x) < 10000 && Math.abs(p.z) < 10000;
};
function ringValid(ring: unknown): ring is Point2[] {
  return Array.isArray(ring) && ring.length >= 3 && ring.length <= 1500 &&
    ring.every(pointValid);
}
function anchorAgrees(a: GeoAnchor, b: GeoAnchor): boolean {
  return Math.abs(a.latitude - b.latitude) <= 1e-7 &&
    Math.abs(a.longitude - b.longitude) <= 1e-7 &&
    Math.abs(a.elevationMeters - b.elevationMeters) <= 0.001;
}

/** Fail closed on partial/stale/corrupt data, but keep older OSM-only builds usable. */
export function isCampusSiteData(
  input: unknown, map: Pick<WorldMap, 'anchor' | 'collectedAt'>
): input is CampusSiteData {
  if (!input || typeof input !== 'object') return false;
  const data = input as Partial<CampusSiteData>;
  return data.schemaVersion === 1 && data.source === 'OpenStreetMap' &&
    typeof data.collectedAt === 'string' && data.collectedAt === map.collectedAt &&
    !!data.anchor && Number.isFinite(data.anchor.latitude) &&
    Number.isFinite(data.anchor.longitude) &&
    Number.isFinite(data.anchor.elevationMeters) &&
    anchorAgrees(data.anchor, map.anchor) &&
    Array.isArray(data.sites) && data.sites.length <= 200 &&
    data.sites.every(s => s && /^(way|relation)\/[1-9]\d*$/.test(s.sourceId) &&
      typeof s.kind === 'string' && s.kind.length > 0 && s.kind.length < 100 &&
      typeof s.name === 'string' && s.name.trim().length > 0 &&
      s.name.length <= 90 && ringValid(s.outline) &&
      Array.isArray(s.holes) && s.holes.length <= 25 &&
      s.holes.every(ringValid));
}

export function isSchoolSite(site: MappedSite): boolean {
  return SCHOOL_KINDS.has(site.kind);
}
export function insideMappedSite(point: Point2, site: MappedSite): boolean {
  return pointInFootprint(point, site.outline) &&
    !site.holes.some(hole => pointInFootprint(point, hole));
}
function comparableName(name: string): string {
  return name.toLocaleLowerCase('bg').replace(/[^\p{L}\p{N}]+/gu, ' ').trim();
}

/**
 * A landmark may be mapped as a named node inside a separately mapped campus.
 * A nearby bank or unrelated school's POI must NEVER borrow its building IDs.
 */
export function mappedSchoolForLandmark(
  landmark: Landmark, sites: readonly MappedSite[]
): MappedSite | null {
  if (!SCHOOL_KINDS.has(landmark.kind)) return null;
  return sites.find(site => isSchoolSite(site) &&
    site.kind === landmark.kind &&
    (site.sourceId === landmark.id ||
      (comparableName(site.name) === comparableName(landmark.name) &&
        insideMappedSite(landmark.point, site)))) ?? null;
}
export function mappedBuildingsOnCampus(
  site: MappedSite, buildings: readonly BuildingFootprint[]
): BuildingFootprint[] {
  return buildings.filter(building => {
    const { outline } = building;
    if (outline.length < 3) return false;
    const centre = outline.reduce(
      (acc, p) => ({ x: acc.x + p.x, z: acc.z + p.z }), { x: 0, z: 0 }
    );
    return insideMappedSite({
      x: centre.x / outline.length,
      z: centre.z / outline.length
    }, site);
  });
}

function closedRing(ring: readonly Point2[]): [number, number][] {
  const coords: [number, number][] = ring.map(p => [p.x, p.z]);
  const first = coords[0], last = coords[coords.length - 1];
  if (first[0] !== last[0] || first[1] !== last[1]) coords.push([...first]);
  return coords;
}
function planarArea(points: readonly Point2[]): number {
  return Math.abs(points.reduce((sum, p, index) => {
    const next = points[(index + 1) % points.length];
    return sum + p.x * next.z - next.x * p.z;
  }, 0)) / 2;
}
export interface CampusSurfaceGeometry {
  positions: number[];
  normals: number[];
  indices: number[];
  boundaryRings: Point2[][];
}

/**
 * A translucent site tint at ground level; roads remain above it, buildings
 * remain untouched, polygon holes stay open. Clipped to the existing 1km².
 * No new collider, fences, entrances, doors, windows or survey claims.
 */
export function buildCampusSurface(site: MappedSite): CampusSurfaceGeometry | null {
  if (!isSchoolSite(site) || !ringValid(site.outline) ||
      !Array.isArray(site.holes) || site.holes.length > 25 ||
      !site.holes.every(ringValid)) return null;
  const input = [closedRing(site.outline),
    ...site.holes.map(closedRing)];
  let clipped: number[][][][];
  try {
    clipped = polygonClipping.intersection(input, [RECT]);
  } catch {
    return null;
  }
  const positions: number[] = [];
  const normals: number[] = [];
  const indices: number[] = [];
  const boundaryRings: Point2[][] = [];

  for (const polygon of clipped) {
    if (!Array.isArray(polygon) || polygon.length < 1) continue;
    const flat: number[] = [];
    const holes: number[] = [];
    const rings: Point2[][] = [];
    for (let i = 0; i < polygon.length; i++) {
      const ring: Point2[] = polygon[i].slice(0, -1)
        .map(([x, z]) => ({ x, z }));
      if (ring.length < 3 || ring.length > 1500 || !ring.every(pointValid)) {
        rings.length = 0;
        break;
      }
      if (i) holes.push(flat.length / 2);
      rings.push(ring);
      for (const p of ring) flat.push(p.x, p.z);
    }
    if (!rings.length || planarArea(rings[0]) < 1 || flat.length / 2 > 3000) continue;
    const faces = earcut(flat, holes);
    if (!faces.length) continue;
    const offset = positions.length / 3;
    for (let i = 0; i < flat.length; i += 2) {
      positions.push(flat[i], 0.018, flat[i + 1]);
      normals.push(0, 1, 0);
    }
    for (let i = 0; i < faces.length; i += 3) {
      const ai = faces[i], bi = faces[i + 1], ci = faces[i + 2];
      const ax = flat[ai * 2], az = flat[ai * 2 + 1];
      const bx = flat[bi * 2], bz = flat[bi * 2 + 1];
      const cx = flat[ci * 2], cz = flat[ci * 2 + 1];
      const crossY = (bz - az) * (cx - ax) - (bx - ax) * (cz - az);
      if (Math.abs(crossY) < 1e-9) continue;
      indices.push(offset + ai, offset + (crossY > 0 ? bi : ci),
        offset + (crossY > 0 ? ci : bi));
    }
    boundaryRings.push(...rings);
  }
  return indices.length ? { positions, normals, indices, boundaryRings } : null;
}
