<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref, watch } from 'vue';
import LocalMap from './components/LocalMap.vue';
import { isWorldMap, type WorldMap } from './world/osm';
import { isNavigationData, type NavigationData } from './world/navigation';
import { isCampusSiteData } from './world/CampusSites';
import type { CampusSiteData } from './world/CampusSites';
import { EuropaGame, type GameStats } from './game/EuropaGame';
import type { ChunkStreamStats } from './world/ChunkStreamer';
import { computed } from 'vue';
import { worldToGeo } from './geo/coordinates';
import { NOVA_ZAGORA_ANCHOR } from './geo/worldConfig';
const canvas = ref<HTMLCanvasElement | null>(null);
const locked = ref(false);
const error = ref('');
const worldMode = ref<'test' | 'osm' | 'stream'>('test');
const stream = ref<ChunkStreamStats>({ current: '—', loaded: 0, desired: 0, loading: 0, failed: 0, available: 0, failedIds: [], lastError: '' });
const stats = ref<GameStats>({ fps: 0, x: 0, y: 0, z: 0, yaw: 0, grounded: false });
const fullMap = ref<WorldMap | null>(null);
const navigation = ref<NavigationData | null>(null);
const rawSites = ref<unknown>(null);
const schoolSites = computed<CampusSiteData | null>(() =>
  fullMap.value && isCampusSiteData(rawSites.value, fullMap.value)
    ? rawSites.value as CampusSiteData : null
);
const overview = ref(false);
const mapAbort = new AbortController();
const previewGeo = computed(() => worldToGeo({ x: stats.value.x, y: 0, z: stats.value.z }, NOVA_ZAGORA_ANCHOR));
const osmUrl = computed(() =>
  'https://www.openstreetmap.org/#map=18/' +
  previewGeo.value.latitude.toFixed(6) + '/' +
  previewGeo.value.longitude.toFixed(6)
);
function onKeyDown(event: KeyboardEvent): void {
  if (event.code === 'KeyM' && !event.repeat && !event.altKey && !event.ctrlKey) {
    overview.value = !overview.value;
  }
}
let game: EuropaGame | null = null;
watch([fullMap, navigation, schoolSites, worldMode], () => {
  if (game && fullMap.value && navigation.value && worldMode.value !== 'test') {
    game.setPoiData(fullMap.value, navigation.value, schoolSites.value);
  }
});
onMounted(() => {
  window.addEventListener('keydown', onKeyDown);
  // This map is local to EUROPA's static host, not a live OSM API request.
  // Its footprint data is small and can guide navigation independently of
  // which 3D chunks are currently active.
  void fetch('/worlds/nova-zagora/map.json', {
    cache: 'no-store', signal: mapAbort.signal
  }).then(async response => {
    if (!response.ok) return;
    const data: unknown = await response.json();
    if (isWorldMap(data)) fullMap.value = data;
  }).catch(error => {
    if (!mapAbort.signal.aborted) console.info('EUROPA: optional navigation map unavailable', error);
  });
  // Served by Vite from local disk. No live OSM requests during gameplay.
  void fetch('/worlds/nova-zagora/navigation.json', {
    cache: 'no-store', signal: mapAbort.signal
  }).then(async response => {
    if (!response.ok) return; // Existing 002C world works without labels.
    const data: unknown = await response.json();
    if (isNavigationData(data, NOVA_ZAGORA_ANCHOR)) navigation.value = data;
    else console.warn('EUROPA: invalid or mismatched OSM navigation metadata.');
  }).catch(error => {
    if (!mapAbort.signal.aborted) console.info('EUROPA: optional street labels unavailable', error);
  });
  // Optional file generated by map:recover --apply; legacy maps without
  // sites.json remain fully playable. Anchor and timestamp checks prevent
  // mixing a stale site's school grounds with a newer world.
  void fetch('/worlds/nova-zagora/sites.json', {
    cache: 'no-store', signal: mapAbort.signal
  }).then(async response => {
    if (!response.ok) return;
    rawSites.value = await response.json() as unknown;
  }).catch(fetchError => {
    if (!mapAbort.signal.aborted) console.info('EUROPA: optional mapped campus grounds unavailable', fetchError);
  });
  if (!canvas.value) return;
  game = new EuropaGame(canvas.value, {
    onStats: value => { stats.value = value; },
    onLockChange: value => { locked.value = value; },
    onError: message => { error.value = message; },
    onWorldChange: mode => { worldMode.value = mode; },
    onStreamStats: status => { stream.value = status; }
  });
});
onBeforeUnmount(() => {
  mapAbort.abort();
  window.removeEventListener('keydown', onKeyDown);
  game?.dispose(); game = null;
});
function start(): void { game?.requestPointerLock(); }
</script>
<template>
  <main class="viewport">
    <canvas ref="canvas" class="game-canvas" @click="start" aria-label="EUROPA 3D game viewport" />
    <header class="hud-top"><div class="brand">EUROPA <span>002D.3B</span></div><div class="sub">{{ worldMode === 'stream' ? 'STREAMED REAL-WORLD GEOMETRY' : worldMode !== 'test' ? 'STATIC OSM WORLD · RUN pnpm map:chunks' : 'TEST ENVIRONMENT · IMPORT PENDING' }}</div></header>
    <div class="stats" aria-live="off"><strong>{{ stats.fps }}</strong> FPS <span class="separator">·</span> X {{ stats.x.toFixed(1) }} · Y {{ stats.y.toFixed(1) }} · Z {{ stats.z.toFixed(1) }} <span class="separator">·</span> {{ stats.grounded ? 'GROUNDED' : 'AIRBORNE' }}</div>
    <div class="geo-preview" :title="worldMode !== 'test' ? 'Real OSM planimetric geometry; flat elevation is not yet implemented' : 'Simulated projection only — run pnpm map:fetch to import real roads and buildings'">{{ worldMode !== 'test' ? 'OSM GEO PREVIEW · FLAT TERRAIN' : 'GEO PREVIEW (SIMULATED)' }} · {{ previewGeo.latitude.toFixed(6) }}° N · {{ previewGeo.longitude.toFixed(6) }}° E</div>
    <div v-if="worldMode === 'stream'" class="stream-debug" aria-live="off"
      :class="{ 'stream-debug--failed': stream.failed > 0 }"
      :title="stream.failed ? 'Failed tile: ' + stream.failedIds.join(', ') + ' · ' + stream.lastError : 'World streaming operating normally'">
      TILE {{ stream.current }} · {{ stream.loaded }}/{{ stream.available }} loaded · {{ stream.loading }} loading · {{ stream.failed }} failed
      <template v-if="stream.failed"> ({{ stream.failedIds.join(', ') }}) · PRESS T TO RETRY</template>
    </div>
    <LocalMap v-if="worldMode !== 'test' && fullMap" :map="fullMap" :navigation="navigation" :sites="schoolSites" :x="stats.x" :z="stats.z" :yaw="stats.yaw" :overview="overview" />
    <a v-if="worldMode !== 'test'" class="osm-location" :href="osmUrl" target="_blank" rel="noopener noreferrer">VIEW LOCATION ON OPENSTREETMAP ↗</a>
    <div v-if="error" style="position:absolute;top:90px;left:24px;right:24px;padding:16px;background:#5b1414;color:white;z-index:30;overflow-wrap:anywhere">Game engine error: {{ error }} — press F12 for details.</div>
    <div v-if="locked" class="crosshair" aria-hidden="true">+</div>
    <section v-if="!locked" class="start-overlay" @click="start">
      <div class="start-card">
        <div class="eyebrow">PROTOTYPE BUILD 0.1</div>
        <h1>THE WORLD<br />AFTER THE FALL.</h1>
        <p>{{ worldMode === 'stream' ? 'Explore OSM Nova Zagora. World tiles load and unload as you move. Elevation and building interiors are not implemented.' : worldMode === 'osm' ? 'Explore the static OSM prototype. Run pnpm map:chunks to enable streaming.' : 'This is the synthetic environment. Run pnpm map:fetch --osm-api to import real Nova Zagora streets.' }}</p>
        <button type="button" @click.stop="start">CLICK TO ENTER <span>→</span></button>
        <div class="controls">WASD — Move <span>·</span> Mouse — Look <span>·</span> Shift — Sprint <span>·</span> Space — Jump <span>·</span> R — Unstick <span>·</span> T — Retry chunks <span>·</span> M — Map <span>·</span> Esc — Pause</div>
      </div>
    </section>
    <footer class="footer"><template v-if="worldMode !== 'test'">NOVA ZAGORA · MAP DATA <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap contributors · ODbL 1.0</a></template><template v-else>NOVA ZAGORA · TEST WORLD · RUN pnpm map:fetch</template></footer>
  </main>
</template>
